defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-cifar-10-linear"
pretrained_feature_extractor: "/media/omnisky/sdb/grade2020/zhangjizhe/ssl_model/results/trained_models/byol/b56kcpbq/byol-cf10-base-b56kcpbq-ep=1020.ckpt"
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: cifar10
  train_path: "../datasets/CIFAR10/train"
  val_path: "../datasets/CIFAR10/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.15
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [6,7]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
